/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-tertiary-fixed': '#2d1602',
        'inverse-surface': '#2c3041',
        'surface-container-high': '#e4e7fe',
        'on-secondary-fixed': '#130d58',
        'tertiary': '#7a573c',
        'on-primary': '#ffffff',
        'surface-dim': '#d6d9ef',
        'surface-container-lowest': '#ffffff',
        'error-container': '#ffdad6',
        'inverse-on-surface': '#eff0ff',
        'secondary': '#58569e',
        'on-tertiary-fixed-variant': '#5f4026',
        'secondary-fixed-dim': '#c3c0ff',
        'outline': '#727970',
        'tertiary-fixed-dim': '#ebbe9c',
        'on-error': '#ffffff',
        'primary-fixed': '#bfeec3',
        'on-surface': '#171b2b',
        'on-tertiary-container': '#4c2f17',
        'on-background': '#171b2b',
        'surface-bright': '#faf8ff',
        'on-primary-container': '#133d20',
        'surface-tint': '#3d6846',
        'on-secondary': '#ffffff',
        'surface': '#faf8ff',
        'background': '#faf8ff',
        'on-primary-fixed': '#00210b',
        'primary-container': '#7ca982',
        'surface-container': '#ebedff',
        'on-surface-variant': '#414941',
        'on-secondary-fixed-variant': '#403e84',
        'secondary-fixed': '#e2dfff',
        'on-secondary-container': '#413f85',
        'outline-variant': '#c1c9bf',
        'tertiary-fixed': '#ffdcc3',
        'error': '#ba1a1a',
        'surface-container-low': '#f3f2ff',
        'tertiary-container': '#c09677',
        'primary': '#3d6846',
        'surface-container-highest': '#dee1f8',
        'surface-variant': '#dee1f8',
        'secondary-container': '#b0aefd',
        'primary-fixed-dim': '#a3d2a8',
        'on-primary-fixed-variant': '#254f30',
        'on-error-container': '#93000a',
        'inverse-primary': '#a3d2a8',
        'on-tertiary': '#ffffff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin': '1rem',
        'space-xl': '2rem',
        'space-md': '1rem',
        'space-xs': '0.25rem',
        'gutter': '1rem',
        'space-lg': '1.5rem',
        'space-sm': '0.5rem',
      },
      fontFamily: {
        'headline-xl-mobile': ['Plus Jakarta Sans', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'headline-xl': ['Plus Jakarta Sans', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'headline-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-md': ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'headline-xl-mobile': ['1.75rem', { lineHeight: '2.25rem', letterSpacing: '-0.015em', fontWeight: '700' }],
        'body-md': ['0.875rem', { lineHeight: '1.45rem', fontWeight: '400' }],
        'body-lg': ['1rem', { lineHeight: '1.6rem', fontWeight: '400' }],
        'body-sm': ['0.75rem', { lineHeight: '1.25rem', fontWeight: '400' }],
        'headline-xl': ['2.25rem', { lineHeight: '2.75rem', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-md': ['0.875rem', { lineHeight: '1.25rem', letterSpacing: '0.01em', fontWeight: '500' }],
        'headline-lg': ['1.75rem', { lineHeight: '2.25rem', letterSpacing: '-0.015em', fontWeight: '600' }],
        'label-sm': ['0.75rem', { lineHeight: '1rem', letterSpacing: '0.02em', fontWeight: '600' }],
        'headline-lg-mobile': ['1.375rem', { lineHeight: '1.75rem', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-sm': ['1.125rem', { lineHeight: '1.5rem', fontWeight: '600' }],
        'headline-md': ['1.25rem', { lineHeight: '1.625rem', letterSpacing: '-0.01em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
